# Use postgres/example user/password credentials
version: '3.1'
services:
  dbpostgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: twitter_data
      POSTGRES_PASSWORD: test1234
    ports:
      - 5432:5432

  dbdynamo:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
